config/routes.rb
Rails.application.routes.draw do
	resources :all_reports, only: [:index]
	resources :user_groups, except: [:show]
	resources :projects, except: [:show]
	resources :users, except: [:show]
	resources :user_settings, only: [:edit, :update]
	resources :sessions, only: [:new, :create, :destroy]
	resources :week_reports, except: [:show]

	root 'week_reports#index'
	match '/signin',  to: 'sessions#new',				via: 'get'
	match '/signout', to: 'sessions#destroy',			via: 'delete'
	match '/change_week',  to: 'week_reports#change_week',		via: 'get'
	match '/copy_item',  to: 'week_reports#copy_item',		via: 'get'
	match '/search_week_or_month',  to: 'all_reports#search_week_or_month',		via: 'post'
	match '/change_week_or_month',  to: 'all_reports#change_week_or_month',		via: 'get'
	match '/filter_project',  to: 'all_reports#filter_project',		via: 'post'
	match '/filter_member',  to: 'all_reports#filter_member',		via: 'post'
	match '/filter_group',  to: 'all_reports#filter_group',		via: 'post'

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
	before_action :signed_in_user
	before_action :set_user_group, only: [:show, :edit, :update, :destroy]
	def index
		@user_groups = UserGroup.all
	end
	def new
		@user_group = UserGroup.new
	end
	def edit
	end
	def create
		@user_group = user_group.new(user_group_params)
		if @user_group.save
			flash[:success] = "新しい項目が追加されました！"
		else
			flash[:error] = "入力値が不正です！"
		end
		redirect_to controller:'user_groups', action:'index'
	end
	def update
		if @user_group.update(user_group_params)
			flash[:success] = "正しく更新されました！"
		else
			flash[:error] = "入力値が不正です！"
		end
		redirect_to controller:'user_groups', action:'index'
	end
	def destroy
		@user_group.destroy
		flash[:success] = "正しく削除されました！"
		redirect_to controller:'user_groups', action:'index'
	end
	private
	def set_user_group
		@user_group = UserGroup.find(params[:id])
	end
	def user_group_params
		params.require(:user_group).permit(:code, :name)
	end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_error_messages.html.erb
<% if @user_group.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user_group.errors.count, "error") %>.
		</div>
		<ul>
			<% @user_group.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/user_groups/edit.html.erb
<h4 class="text-center m-bottom">グループの情報を更新しましょう</h4>

<div class="row m-bottom">
	<div class="text-center col-md-4 col-md-offset-4">
		<%= form_for(@user_group) do |f| %>
		<%= render 'error_messages' %>
		<%= f.label :name, "グループ名" %>
		<%= f.text_field :name, class: "form-control text-center", required: true %>
		<%= f.submit "更新する", class: "btn btn-lg btn-primary btn-block m-bottom" %>
		<%= link_to '前に戻る', user_groups_path, class: "btn btn-lg btn-danger btn-block" %>
	<% end %>
	</div>
</div>

app/views/user_groups/index.html.erb
<div class="row">
	<h3 class="text-center m-bottom">グループ一覧</h3>
	<section class="text-center">
		<%= link_to 'グループを追加する', new_user_group_path, class: "btn btn-success btn-lg" %>
	</section>
	<table class="table">
		<thead>
			<tr>
				<th>グループ名</th>
				<th>更新日時</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
			<% @user_groups.each do |user_group| %>
			<tr>
				<td><%= user_group.name %></td>
				<td><%= user_group.updated_at %></td>
				<td>
					<%= link_to '編集する', edit_user_group_path(user_group), class: "btn btn-primary" %>
					<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal<%= user_group.id %>">削除する</button>
					<div class="modal fade" id="modal<%= user_group.id %>" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-body">本当に削除しますか？</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
									<%= link_to '削除', user_group, method: :delete, class: "btn btn-danger" %>
								</div>
							</div>
						</div>
					</div>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<br>
</div>

app/views/user_groups/new.html.erb
<h4 class="text-center m-bottom">新しいグループをつくりましょう</h4>

<div class="row m-bottom">
	<div class="text-center col-md-4 col-md-offset-4">
		<%= form_for(@user_group) do |f| %>
		<%= render 'error_messages' %>
		<%= f.label :name, "グループ名" %>
		<%= f.text_field :name, class: "form-control text-center", required: true %>
		<%= f.submit "作成する", class: "btn btn-lg btn-primary btn-block m-bottom" %>
		<%= link_to '前に戻る', user_groups_path, class: "btn btn-lg btn-danger btn-block" %>
		<% end %>
	</div>
</div>