config/routes.rb
Rails.application.routes.draw do
	resources :all_reports, only: [:index]
	resources :user_groups, except: [:show]
	resources :projects, except: [:show]
	resources :users, except: [:show]
	resources :user_settings, only: [:edit, :update]
	resources :sessions, only: [:new, :create, :destroy]
	resources :week_reports, except: [:show]

	root 'week_reports#index'
	match '/signin',  to: 'sessions#new',				via: 'get'
	match '/signout', to: 'sessions#destroy',			via: 'delete'
	match '/change_week',  to: 'week_reports#change_week',		via: 'get'
	match '/copy_item',  to: 'week_reports#copy_item',		via: 'get'
	match '/search_week_or_month',  to: 'all_reports#search_week_or_month',		via: 'post'
	match '/change_week_or_month',  to: 'all_reports#change_week_or_month',		via: 'get'
	match '/filter_project',  to: 'all_reports#filter_project',		via: 'post'
	match '/filter_member',  to: 'all_reports#filter_member',		via: 'post'
	match '/filter_group',  to: 'all_reports#filter_group',		via: 'post'

end

app/views/groups/edit.html.erb
<h4 class="text-center m-bottom">グループの情報を更新しましょう</h4>

<div class="row m-bottom">
	<div class="text-center col-md-4 col-md-offset-4">
		<%= form_for(@group) do |f| %>
		<%= render 'error_messages' %>
		<%= f.label :name, "グループ名" %>
		<%= f.text_field :name, class: "form-control text-center", required: true %>
		<%= f.submit "更新する", class: "btn btn-lg btn-primary btn-block m-bottom" %>
		<%= link_to '前に戻る', groups_path, class: "btn btn-lg btn-danger btn-block" %>
	<% end %>
	</div>
</div>

app/views/groups/index.html.erb
<div class="row">
	<h3 class="text-center m-bottom">グループ一覧</h3>
	<section class="text-center">
		<%= link_to 'グループを追加する', new_group_path, class: "btn btn-success btn-lg" %>
	</section>
	<table class="table p-top">
		<thead>
			<tr>
				<th>グループ名</th>
				<th>更新日時</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
			<% @groups.each do |group| %>
			<tr>
				<td><%= group.name %></td>
				<td><%= group.updated_at %></td>
				<td>
					<%= link_to '編集する', edit_group_path(group), class: "btn btn-primary" %>
					<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#conf-box">削除する</button>
					<div class="modal fade" id="conf-box" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-body">本当に削除しますか？</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
									<%= link_to '削除', group, method: :delete, class: "btn btn-danger" %>
								</div>
							</div>
						</div>
					</div>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<br>
</div>

app/views/groups/new.html.erb
<h4 class="text-center m-bottom">新しいグループをつくりましょう</h4>

<div class="row m-bottom">
	<div class="text-center col-md-4 col-md-offset-4">
		<%= form_for(@group) do |f| %>
		<%= render 'error_messages' %>
		<%= f.label :name, "グループ名" %>
		<%= f.text_field :name, class: "form-control text-center", required: true %>
		<%= f.submit "作成する", class: "btn btn-lg btn-primary btn-block m-bottom" %>
		<%= link_to '前に戻る', groups_path, class: "btn btn-lg btn-danger btn-block" %>
		<% end %>
	</div>
</div>